server:
  port: 10000
spring:
  application:
    name: ApiGateway
  cloud:
    gateway:
      routes[0]:
        id: test
        uri: lb://UserMicroservice
        predicates[0]: Path=/test
        predicates[1]: Method=GET
        predicates[2]: Header=Authorization, Bearer (.*)
        filters[0]: RemoveRequestHeader=Cookie
        filters[1]: CustomFilter
      routes[1]:
        id: test2
        uri: lb://UserMicroservice
        predicates[0]: Path=/test2
        predicates[1]: Method=GET
        predicates[2]: Header=Authorization, Bearer (.*)
        filters[0]: RemoveRequestHeader=Cookie
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka
  instance:
    preferIpAddress: true