server:
  port: 8010
spring:
  application:
    name: ConfigServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chidinma-elekwachi/niit-config-repo
          username: chidinma-elekwachi
          password: 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
#          cloneOnStart: true
          #defaultLabel: master
