server:
  port: 0
spring:
  application:
    name: ProductMicroservice
  config:
    import: http://localhost:8010
  datasource:
    generateUniqueName: false
    name: product-db
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka
  instance:
    preferIpAddress: true
