server:
  port: 0
spring:
  application:
    name: ProductMicroservice
  config:
    import: optional:configserver:http://localhost:8010
  datasource:
    generateUniqueName: false
    name: product-db
  h2:
    console:
      enabled: true
      settings:
        webAllowOthers: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka
  instance:
    preferIpAddress: true
